#spring.servlet.multipart.max-file-size=128KB
#spring.servlet.multipart.max-request-size=128KB
server:
  port: 9000

spring:
  h2:
    console:
      path: /h2_console
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: ALWAYS
